package treeftp;

import java.io.IOException;

public class NoArgsException extends IOException
{
	private static final long serialVersionUID = -5705364872060201926L; // automatically generated by Eclipse IDE

	public NoArgsException(String message)
	{
		super(message);
	}	
}
